version: "3"

tasks:
  build:
    desc: "Build the bot binary"
    cmds:
      - go build -o bin/tg-hamster ./cmd/tg-hamster

  test:
    desc: "Run unit tests"
    cmds:
      - go test ./... -v

  lint:
    desc: "Run golangci-lint"
    cmds:
      - golangci-lint run ./...

  docker-build:
    desc: "Build Docker image"
    cmds:
      - docker build -t teleta/tg-hamster:latest .

  docker-up:
    desc: "Start docker-compose"
    cmds:
      - docker-compose up -d

  docker-down:
    desc: "Stop docker-compose"
    cmds:
      - docker-compose down
