version: '3'

vars:
  bin: "tg-hamster"

tasks:
  build:
    desc: "build binary"
    cmds:
      - go build -o tg-hamster main.go

  docker-build:
    desc: "build docker image"
    cmds:
      - docker build -t teleta/tg-hamster:latest .

  docker-push:
    desc: "push docker image"
    cmds:
      - docker push teleta/tg-hamster:latest

  release:
    desc: "run goreleaser (local)"
    cmds:
      - goreleaser release --rm-dist
