version: "3"

vars:
  bin: "tg-hamster"

tasks:
  build:
    desc: "build binary"
    cmds:
      - go build -o ./dist/{{.bin}} main.go

  docker-build:
    desc: "build docker image"
    cmds:
      - docker build -t ${DOCKER_IMAGE:teleta/tg-hamster:latest} .

  docker-push:
    desc: "push docker image (set DOCKER_IMAGE and ensure docker login)"
    cmds:
      - docker push ${DOCKER_IMAGE:teleta/tg-hamster:latest}

  release:
    desc: "run goreleaser (local)"
    cmds:
      - goreleaser release --rm-dist
