name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Установка Go 1.25 для сборки и тестов
      - name: Set up Go 1.25
        uses: actions/setup-go@v4
        with:
          go-version: 1.25.3

      - name: Build bot
        run: go build -v ./...

      - name: Run Tests (Go 1.25)
        run: go test ./... -v

      # Установка Go 1.24 для golangci-lint
      - name: Set up Go 1.24 for linter
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
            | sh -s -- -b $HOME/go/bin v1.64.2
          echo "$HOME/go/bin" >> $GITHUB_PATH
          golangci-lint --version

      - name: Run Linter (Go 1.24)
        run: golangci-lint run ./...
