name: CI/CD

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      GOBIN: $HOME/go/bin

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ===========================
      # Сборка и тесты (Go 1.25)
      # ===========================
      - name: Set up Go 1.25
        uses: actions/setup-go@v4
        with:
          go-version: 1.25.3

      - name: Build binary
        run: |
          mkdir -p bin
          go build -v -o bin/tg-hamster ./cmd/tg-hamster

      - name: Run Tests
        run: go test ./... -v

      # ===========================
      # Линтинг (Go 1.25.1)
      # ===========================
#      - name: Set up Go 1.25.1 for linter
#        uses: actions/setup-go@v4
#        with:
#          go-version: 1.25.1
#
#      - name: Install golangci-lint
#        run: |
#          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
#            | sh -s -- -b $HOME/go/bin v1.64.8
#          echo "$HOME/go/bin" >> $GITHUB_PATH
#          golangci-lint --version
#      - name: Show PATH
#        run: echo $PATH
#
#      - name: Run Linter
#        run: golangci-lint run ./...

      # ===========================
      # Docker Build & Push
      # ===========================
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t teleta/tg-hamster:latest .

      - name: Push Docker image (latest)
        run: docker push teleta/tg-hamster:latest

      - name: Tag & Push Docker image by version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          docker tag teleta/tg-hamster:latest teleta/tg-hamster:$VERSION
          docker push teleta/tg-hamster:$VERSION
