name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.25.3

      - name: Set Go environment
        run: |
          echo "GO111MODULE=on" >> $GITHUB_ENV

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
            | sh -s -- -b $HOME/go/bin v1.58.0
          echo "$HOME/go/bin" >> $GITHUB_PATH
          golangci-lint --version

      - name: Build
        run: make build || go build -o bin/tg-hamster ./cmd/tg-hamster

      - name: Run tests
        run: go test ./... -v

      - name: Run linter
        run: golangci-lint run ./...
